package librarian.gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import librarian.handlers.BookHandler;
import librarian.handlers.LendHandler;
import librarian.handlers.LogHandler;
import librarian.handlers.UsersHandler;
import librarian.utils.User;

/**
 *
 * @author Miltiadis Parcharidis 011873
 */
public class LendBook extends javax.swing.JFrame {

    /**
     * Creates new form ViewUsers
     */
    private ArrayList userIds = new ArrayList();

    public LendBook() {
        initComponents();

        userIds.add(""); // for consistency between this list and the combobox list which starts from 0 index
        ResultSet rsU = UsersHandler.selectUser(0, -1, null);
        customerCombo.addItem("- Select Customer -");
        String userData = "";
        try {

            while (rsU.next()) {
                if (rsU.getInt(8) != 0) { // disabled user
                    userIds.add(rsU.getString(1));
                    userData = "ID: " + rsU.getString(1) + " " + rsU.getString(2) + " " + rsU.getString(3);
                    customerCombo.addItem(userData);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(LendBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        customerCombo.setSelectedIndex(0);

        showBooks(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAbout = new javax.swing.JDialog();
        panelAbout = new javax.swing.JPanel();
        buttonOK = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaAbout = new javax.swing.JTextArea();
        dialogHelp = new javax.swing.JDialog();
        panelHelp = new javax.swing.JPanel();
        buttonHelp = new javax.swing.JButton();
        labelImage1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaHelp = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        musicBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();
        jTableBooks.getTableHeader().setOpaque(false);
        jTableBooks.getTableHeader().setBackground(new java.awt.Color(201,210,216));
        searchTermTxt = new javax.swing.JTextField();
        jComboBoxFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        labelFullname = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        customerCombo = new javax.swing.JComboBox<>();
        lendBtn = new javax.swing.JButton();
        labelCustomer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuViewLog = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuBooks = new javax.swing.JMenu();
        menuLend = new javax.swing.JMenuItem();
        menuReturn = new javax.swing.JMenuItem();
        menuInsert = new javax.swing.JMenuItem();
        menuSearch = new javax.swing.JMenuItem();
        menuAuthors = new javax.swing.JMenu();
        menuAuthorInsert = new javax.swing.JMenuItem();
        menuViewAuthor = new javax.swing.JMenuItem();
        menuUsers = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        dialogAbout.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogAbout.setTitle("About this app");
        dialogAbout.setBackground(new java.awt.Color(156, 193, 194));
        dialogAbout.setUndecorated(true);
        dialogAbout.setResizable(false);
        dialogAbout.setSize(new java.awt.Dimension(439, 242));

        panelAbout.setBackground(new java.awt.Color(156, 193, 194));
        panelAbout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panelAbout.setPreferredSize(new java.awt.Dimension(427, 230));

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/external/images/libraryAbout.png"))); // NOI18N
        labelImage.setToolTipText("Library logo");

        jScrollPane2.setHorizontalScrollBar(null);

        textAreaAbout.setEditable(false);
        textAreaAbout.setBackground(new java.awt.Color(156, 193, 194));
        textAreaAbout.setColumns(20);
        textAreaAbout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textAreaAbout.setForeground(new java.awt.Color(140, 112, 104));
        textAreaAbout.setRows(5);
        textAreaAbout.setText("Librarian App\n\nCreated by SoftGen Inc.\n\nversion: 1.41\nRelease date: 01/12/2024");
        textAreaAbout.setToolTipText("About this application");
        textAreaAbout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 210, 216), 3, true));
        textAreaAbout.setMargin(new java.awt.Insets(6, 6, 6, 6));
        textAreaAbout.setSelectedTextColor(new java.awt.Color(201, 210, 216));
        textAreaAbout.setSelectionColor(new java.awt.Color(140, 112, 104));
        jScrollPane2.setViewportView(textAreaAbout);

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(buttonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOK)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogAboutLayout = new javax.swing.GroupLayout(dialogAbout.getContentPane());
        dialogAbout.getContentPane().setLayout(dialogAboutLayout);
        dialogAboutLayout.setHorizontalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAboutLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        dialogAboutLayout.setVerticalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAboutLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        dialogHelp.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogHelp.setTitle("About this app");
        dialogHelp.setBackground(new java.awt.Color(156, 193, 194));
        dialogHelp.setUndecorated(true);
        dialogHelp.setResizable(false);
        dialogHelp.setSize(new java.awt.Dimension(584, 297));

        panelHelp.setBackground(new java.awt.Color(156, 193, 194));
        panelHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panelHelp.setPreferredSize(new java.awt.Dimension(427, 230));

        buttonHelp.setText("OK");
        buttonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHelpActionPerformed(evt);
            }
        });

        labelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/external/images/libraryAbout.png"))); // NOI18N
        labelImage1.setToolTipText("Library logo");

        jScrollPane3.setHorizontalScrollBar(null);

        textAreaHelp.setEditable(false);
        textAreaHelp.setBackground(new java.awt.Color(156, 193, 194));
        textAreaHelp.setColumns(20);
        textAreaHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textAreaHelp.setForeground(new java.awt.Color(140, 112, 104));
        textAreaHelp.setLineWrap(true);
        textAreaHelp.setRows(5);
        textAreaHelp.setText("• Use Alt+key mnemonic for buttons\n\n• Use Ctrl+key for Menu shortcuts\n\n• Music can be turned off and on using the playback button on the lower right corner (shortcut Alt+M)\n\n• Always logout before closing the app");
        textAreaHelp.setToolTipText("About this application");
        textAreaHelp.setWrapStyleWord(true);
        textAreaHelp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 210, 216), 3, true));
        textAreaHelp.setMargin(new java.awt.Insets(6, 6, 6, 6));
        textAreaHelp.setSelectedTextColor(new java.awt.Color(201, 210, 216));
        textAreaHelp.setSelectionColor(new java.awt.Color(140, 112, 104));
        jScrollPane3.setViewportView(textAreaHelp);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(140, 112, 104));
        jLabel4.setText("Navigation Quick Tips");

        javax.swing.GroupLayout panelHelpLayout = new javax.swing.GroupLayout(panelHelp);
        panelHelp.setLayout(panelHelpLayout);
        panelHelpLayout.setHorizontalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelHelpLayout.createSequentialGroup()
                        .addGroup(panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonHelp)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelHelpLayout.setVerticalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHelpLayout.createSequentialGroup()
                        .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHelpLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(buttonHelp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogHelpLayout = new javax.swing.GroupLayout(dialogHelp.getContentPane());
        dialogHelp.getContentPane().setLayout(dialogHelpLayout);
        dialogHelpLayout.setHorizontalGroup(
            dialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        dialogHelpLayout.setVerticalGroup(
            dialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHelpLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Browse Library Books");
        setBackground(new java.awt.Color(156, 193, 194));
        setResizable(false);
        setSize(new java.awt.Dimension(950, 750));

        jPanel2.setBackground(new java.awt.Color(156, 193, 194));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(950, 750));

        musicBtn.setMnemonic('M');
        musicBtn.setText("\u25A0");
        if (User.isMusicPlaying()) {
            musicBtn.setText("\u25A0");
        }
        else {
            musicBtn.setText("\u25B6");
        }
        musicBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musicBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musicBtnMouseExited(evt);
            }
        });
        musicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 112, 104));
        jLabel1.setText("Quick Lend");

        backBtn.setMnemonic('B');
        backBtn.setText("<< Back");
        backBtn.setToolTipText("Return to main menu");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Category", "Publishing House", "ISBN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBooks.setToolTipText("Available books");
        jTableBooks.setPreferredSize(new java.awt.Dimension(900, 700));
        jTableBooks.setRequestFocusEnabled(false);
        jTableBooks.setSelectionBackground(new java.awt.Color(201, 210, 216));
        jTableBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableBooks.setShowGrid(true);
        jTableBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBooks);
        if (jTableBooks.getColumnModel().getColumnCount() > 0) {
            jTableBooks.getColumnModel().getColumn(0).setMinWidth(40);
            jTableBooks.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableBooks.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableBooks.getColumnModel().getColumn(1).setMinWidth(260);
            jTableBooks.getColumnModel().getColumn(1).setPreferredWidth(260);
            jTableBooks.getColumnModel().getColumn(1).setMaxWidth(260);
            jTableBooks.getColumnModel().getColumn(2).setMinWidth(110);
            jTableBooks.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTableBooks.getColumnModel().getColumn(2).setMaxWidth(110);
            jTableBooks.getColumnModel().getColumn(3).setMinWidth(180);
            jTableBooks.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTableBooks.getColumnModel().getColumn(3).setMaxWidth(180);
            jTableBooks.getColumnModel().getColumn(4).setMinWidth(100);
            jTableBooks.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableBooks.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        searchTermTxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        searchTermTxt.setText("search here");
        searchTermTxt.setToolTipText("Enter terms for searching");
        searchTermTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTermTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTermTxtFocusLost(evt);
            }
        });
        searchTermTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTermTxtActionPerformed(evt);
            }
        });

        jComboBoxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Category", "Publishing House", "ISBN" }));
        jComboBoxFilter.setToolTipText("Select your filter");
        jComboBoxFilter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxFilterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxFilterFocusLost(evt);
            }
        });
        jComboBoxFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFilterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 112, 104));
        jLabel2.setText("Filter");

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/external/images/searchLens.png"))); // NOI18N
        searchBtn.setToolTipText("Search with the given terms");
        searchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnMouseExited(evt);
            }
        });
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        labelFullname.setText(User.getName() + " " + User.getSurname());
        labelFullname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFullname.setText(User.getName() + " " + User.getSurname());
        labelFullname.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        logOutBtn.setBackground(new java.awt.Color(156, 193, 194));
        logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setMnemonic('L');
        logOutBtn.setText("Log Out");
        logOutBtn.setToolTipText("Safely logout from the application");
        logOutBtn.setBorder(null);
        logOutBtn.setBorderPainted(false);
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        customerCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerComboFocusLost(evt);
            }
        });
        customerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboActionPerformed(evt);
            }
        });

        lendBtn.setText("Lend Book(s)");
        lendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lendBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lendBtnMouseExited(evt);
            }
        });
        lendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendBtnActionPerformed(evt);
            }
        });

        labelCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCustomer.setForeground(new java.awt.Color(193, 81, 135));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 112, 104));
        jLabel3.setText("Customer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOutBtn)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(searchTermTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lendBtn)
                                .addGap(284, 284, 284)
                                .addComponent(labelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(musicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logOutBtn)
                            .addComponent(labelFullname)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchTermTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lendBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(musicBtn))
                .addGap(15, 15, 15))
        );

        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuFile.setMnemonic('O');
        menuFile.setText("File");
        menuFile.setToolTipText("Actions about the Application");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuViewLog.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuViewLog.setMnemonic('g');
        menuViewLog.setText("View Log");
        menuViewLog.setToolTipText("Examine the application log");
        menuViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewLogActionPerformed(evt);
            }
        });
        menuFile.add(menuViewLog);

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLogout.setText("Logout");
        menuLogout.setToolTipText("Exit safely from the application");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuFile.add(menuLogout);

        menuBar.add(menuFile);

        menuBooks.setMnemonic('S');
        menuBooks.setText("Books");
        menuBooks.setToolTipText("Actions about Books");
        menuBooks.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuBooksMenuSelected(evt);
            }
        });
        menuBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBooksMouseEntered(evt);
            }
        });
        menuBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBooksActionPerformed(evt);
            }
        });

        menuLend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLend.setMnemonic('Q');
        menuLend.setText("Lend a Book");
        menuLend.setToolTipText("Lend a book to a user");
        menuLend.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menuLendStateChanged(evt);
            }
        });
        menuLend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLendMouseEntered(evt);
            }
        });
        menuLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLendActionPerformed(evt);
            }
        });
        menuBooks.add(menuLend);

        menuReturn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuReturn.setMnemonic('R');
        menuReturn.setText("Return Book");
        menuReturn.setToolTipText("Return a book to the Library");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        menuBooks.add(menuReturn);

        menuInsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuInsert.setMnemonic('I');
        menuInsert.setText("Register Book");
        menuInsert.setToolTipText("Register a new book to the Library");
        menuInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsertActionPerformed(evt);
            }
        });
        menuBooks.add(menuInsert);

        menuSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSearch.setMnemonic('B');
        menuSearch.setText("Browse Books");
        menuSearch.setToolTipText("Find books based on title");
        menuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearchActionPerformed(evt);
            }
        });
        menuBooks.add(menuSearch);

        menuBar.add(menuBooks);

        menuAuthors.setText("Authors");
        menuAuthors.setToolTipText("Actions about Authors");

        menuAuthorInsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAuthorInsert.setMnemonic('A');
        menuAuthorInsert.setText("Insert Author");
        menuAuthorInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAuthorInsertActionPerformed(evt);
            }
        });
        menuAuthors.add(menuAuthorInsert);

        menuViewAuthor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuViewAuthor.setMnemonic('V');
        menuViewAuthor.setText("View/Edit Author");
        menuViewAuthor.setToolTipText("View or Edit Authors");
        menuViewAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewAuthorActionPerformed(evt);
            }
        });
        menuAuthors.add(menuViewAuthor);

        menuBar.add(menuAuthors);

        menuUsers.setText("Users");
        menuUsers.setToolTipText("Actions about Users");
        menuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsersActionPerformed(evt);
            }
        });

        menuUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUser.setMnemonic('U');
        menuUser.setText("Insert User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        menuUsers.add(menuUser);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("View/Edit User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsers.add(jMenuItem1);

        menuBar.add(menuUsers);

        menuHelp.setText("Help");
        menuHelp.setToolTipText("Find help for issues");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem2.setText("Contents");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuHelp.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setMnemonic('b');
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuHelp.add(jMenuItem4);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchTermTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTermTxtActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_searchTermTxtActionPerformed

    private void jTableBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBooksMouseClicked
        if (evt.getClickCount() == 2 && jTableBooks.getSelectedRow() != -1) {
            lendBtnActionPerformed(null);
        }
    }//GEN-LAST:event_jTableBooksMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        ResultSet rs = null;
        int searchCat = jComboBoxFilter.getSelectedIndex() + 1;
        String searchTerm = "";
        if (!searchTermTxt.getText().equalsIgnoreCase("search here")) {
            searchTerm = searchTermTxt.getText();
        }
        rs = BookHandler.selectBooksWithStock(searchCat, searchTerm);
        showBooks(rs);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void menuViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewLogActionPerformed
        this.setVisible(false);
        ViewLog viewLog = new ViewLog();
        viewLog.setVisible(true);
    }//GEN-LAST:event_menuViewLogActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        try {
            LogHandler.insertActivityLog("User " + User.getUserid() + " "
                    + User.getName() + " " + User.getSurname() + " has logged off");
            User.clearValues();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        Initiator init = new Initiator();
        init.setVisible(true);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed

    }//GEN-LAST:event_menuFileActionPerformed

    private void menuLendStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menuLendStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLendStateChanged

    private void menuLendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLendMouseEntered

    }//GEN-LAST:event_menuLendMouseEntered

    private void menuLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLendActionPerformed
        this.setVisible(false);
        LendBook lendBook = new LendBook();
        lendBook.setVisible(true);
    }//GEN-LAST:event_menuLendActionPerformed

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
        this.setVisible(false);
        ReturnBook returnBook = new ReturnBook();
        returnBook.setVisible(true);
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsertActionPerformed
        this.setVisible(false);
        InsertBook insertBook = new InsertBook();
        insertBook.setVisible(true);
    }//GEN-LAST:event_menuInsertActionPerformed

    private void menuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearchActionPerformed
        this.setVisible(false);
        ViewBooks viewBooks = new ViewBooks();
        viewBooks.setVisible(true);
    }//GEN-LAST:event_menuSearchActionPerformed

    private void menuBooksMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuBooksMenuSelected

    }//GEN-LAST:event_menuBooksMenuSelected

    private void menuBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBooksMouseEntered

    }//GEN-LAST:event_menuBooksMouseEntered

    private void menuBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBooksActionPerformed

    }//GEN-LAST:event_menuBooksActionPerformed

    private void menuAuthorInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAuthorInsertActionPerformed
        this.setVisible(false);
        InsertAuthor insAuth = new InsertAuthor();
        insAuth.setVisible(true);
    }//GEN-LAST:event_menuAuthorInsertActionPerformed

    private void menuViewAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewAuthorActionPerformed
        this.setVisible(false);
        ViewAuthors viewAuthors = new ViewAuthors();
        viewAuthors.setVisible(true);
    }//GEN-LAST:event_menuViewAuthorActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        this.setVisible(false);
        InsertUser insUser = new InsertUser();
        insUser.setVisible(true);
    }//GEN-LAST:event_menuUserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        ViewUsers viewUsers = new ViewUsers();
        viewUsers.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsersActionPerformed

    }//GEN-LAST:event_menuUsersActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dialogAbout.setLocationRelativeTo(this);
        dialogAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        dialogAbout.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        try {
            LogHandler.insertActivityLog("User " + User.getUserid() + " "
                    + User.getName() + " " + User.getSurname() + " has logged off");
            User.clearValues();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        Initiator init = new Initiator();
        init.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void jComboBoxFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFilterActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_jComboBoxFilterActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new java.awt.Color(201, 210, 216));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
    }//GEN-LAST:event_backBtnMouseExited

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new java.awt.Color(193, 81, 135));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new java.awt.Color(156, 193, 194));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void searchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseEntered
        searchBtn.setBackground(new java.awt.Color(201, 210, 216));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12));
    }//GEN-LAST:event_searchBtnMouseEntered

    private void searchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseExited
        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
    }//GEN-LAST:event_searchBtnMouseExited

    private void customerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboActionPerformed
        if (customerCombo.getSelectedIndex() > 0) {
            labelCustomer.setText("");
            customerCombo.setBackground(new java.awt.Color(201, 210, 216));
        }
    }//GEN-LAST:event_customerComboActionPerformed

    private void lendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendBtnActionPerformed

        int bookID = 0, userID = 0;
        int row = jTableBooks.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,
                    "Please select a Book first",
                    "Action needed",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            bookID = Integer.parseInt(jTableBooks.getModel().getValueAt(row, 0).toString());
        }

        int customerComboIndex = customerCombo.getSelectedIndex();
        if (customerComboIndex < 1) {
            labelCustomer.setText("Please select a customer");
            customerCombo.requestFocus();
            customerCombo.setBackground(new java.awt.Color(193, 81, 135));
            return;
        } else {
            labelCustomer.setText("");
            customerCombo.setBackground(new java.awt.Color(255, 255, 255));
        }
        userID = Integer.parseInt(userIds.get(customerComboIndex).toString());

        boolean inserted = LendHandler.insertBookLending(userID, bookID);
        if (inserted) {
            labelCustomer.setText("");
            JOptionPane.showMessageDialog(jPanel2, "The Book(s) is now lend to " + customerCombo.getItemAt(customerComboIndex), "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            labelCustomer.setText("");
            JOptionPane.showMessageDialog(jPanel2, "Error While Lending the book!", "Error", JOptionPane.WARNING_MESSAGE);
        }
        jTableBooks.clearSelection();
        customerCombo.setSelectedIndex(0);
        searchTermTxt.setText("search here");
        searchTermTxt.setFont(new java.awt.Font("Segoe UI", 2, 12));
        showBooks(null);
    }//GEN-LAST:event_lendBtnActionPerformed

    private void lendBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lendBtnMouseEntered
        lendBtn.setBackground(new java.awt.Color(201, 210, 216));
        lendBtn.setFont(new java.awt.Font("Segoe UI", 1, 12));
    }//GEN-LAST:event_lendBtnMouseEntered

    private void lendBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lendBtnMouseExited
        lendBtn.setBackground(new java.awt.Color(255, 255, 255));
        lendBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
    }//GEN-LAST:event_lendBtnMouseExited

    private void searchTermTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTermTxtFocusGained
        if (searchTermTxt.getText().equals("search here")) {
            searchTermTxt.setText("");
            searchTermTxt.setFont(new java.awt.Font("Segoe UI", 0, 12));
        }
        searchTermTxt.setBackground(new java.awt.Color(201, 210, 216));
    }//GEN-LAST:event_searchTermTxtFocusGained

    private void jComboBoxFilterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxFilterFocusGained
        jComboBoxFilter.setBackground(new java.awt.Color(201, 210, 216));
    }//GEN-LAST:event_jComboBoxFilterFocusGained

    private void searchTermTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTermTxtFocusLost
        if (searchTermTxt.getText().equals("")) {
            searchTermTxt.setText("search here");
            searchTermTxt.setFont(new java.awt.Font("Segoe UI", 2, 12));
        }
        searchTermTxt.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_searchTermTxtFocusLost

    private void jComboBoxFilterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxFilterFocusLost
        jComboBoxFilter.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jComboBoxFilterFocusLost

    private void customerComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerComboFocusGained
        customerCombo.setBackground(new java.awt.Color(201, 210, 216));
    }//GEN-LAST:event_customerComboFocusGained

    private void customerComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerComboFocusLost
        if (customerCombo.getSelectedIndex() > 0) {
            customerCombo.setBackground(new java.awt.Color(255, 255, 255));
            labelCustomer.setText("");
        }
    }//GEN-LAST:event_customerComboFocusLost

    private void musicBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicBtnMouseEntered
        musicBtn.setBackground(new java.awt.Color(201, 210, 216));
        if (musicBtn.getText().equalsIgnoreCase("\u25B6")) {
            musicBtn.setToolTipText("Start the music");
        } else {
            musicBtn.setToolTipText("Stop the music");
        }
    }//GEN-LAST:event_musicBtnMouseEntered

    private void musicBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicBtnMouseExited
        musicBtn.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_musicBtnMouseExited

    private void musicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicBtnActionPerformed
        if (musicBtn.getText().equalsIgnoreCase("\u25B6")) {
            User.playMusic();
            musicBtn.setText("\u25A0");
        } else {
            User.stopMusic();
            musicBtn.setText("\u25B6");
        }
    }//GEN-LAST:event_musicBtnActionPerformed

    private void buttonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHelpActionPerformed
        dialogHelp.dispose();
    }//GEN-LAST:event_buttonHelpActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dialogHelp.setLocationRelativeTo(this);
        dialogHelp.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonOK;
    private javax.swing.JComboBox<String> customerCombo;
    private javax.swing.JDialog dialogAbout;
    private javax.swing.JDialog dialogHelp;
    private javax.swing.JComboBox<String> jComboBoxFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JLabel labelCustomer;
    private javax.swing.JLabel labelFullname;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelImage1;
    private javax.swing.JButton lendBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JMenuItem menuAuthorInsert;
    private javax.swing.JMenu menuAuthors;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBooks;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuInsert;
    private javax.swing.JMenuItem menuLend;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JMenuItem menuSearch;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JMenu menuUsers;
    private javax.swing.JMenuItem menuViewAuthor;
    private javax.swing.JMenuItem menuViewLog;
    private javax.swing.JButton musicBtn;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelHelp;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTermTxt;
    private javax.swing.JTextArea textAreaAbout;
    private javax.swing.JTextArea textAreaHelp;
    // End of variables declaration//GEN-END:variables

    private void showBooks(ResultSet rs) {

        DefaultTableModel model = (DefaultTableModel) jTableBooks.getModel();
        model.setRowCount(0);

        if (rs == null) {
            rs = BookHandler.selectBooksWithStock(0, null);
        }

        try {
            while (rs.next()) {
                Object data[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
