package librarian.gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import librarian.handlers.BookHandler;
import librarian.handlers.LendHandler;
import librarian.handlers.LogHandler;
import librarian.handlers.PublHouseHandler;
import librarian.utils.User;

/**
 *
 * @author Miltiadis Parcharidis 011873
 */
public class ViewBook extends javax.swing.JFrame {

    ResultSet rs = null;
    ResultSet rsCat = null;
    ResultSet rsPubHouses = null;
    ResultSet rsLendCat = null;

    public ViewBook() {
        // do nothing
    }

    public ViewBook(int bookID) {
        initComponents();

        fillInFormValues(bookID);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAbout = new javax.swing.JDialog();
        panelAbout = new javax.swing.JPanel();
        buttonOK = new javax.swing.JButton();
        labelImage1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaAbout = new javax.swing.JTextArea();
        jSplitPane = new javax.swing.JSplitPane();
        leftPane = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        rightPane = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        lendCatCombo = new javax.swing.JComboBox<>();
        titleTxt = new javax.swing.JTextField();
        labelPubHouse = new javax.swing.JLabel();
        labelCategory = new javax.swing.JLabel();
        isbnTxt = new javax.swing.JTextField();
        pubHouseCombo = new javax.swing.JComboBox<>();
        cancelBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        pubDateTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        labelPubDate = new javax.swing.JLabel();
        labelLendCat = new javax.swing.JLabel();
        labelIsbn = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelbookID = new javax.swing.JLabel();
        labelFullname = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        labelAuthor = new javax.swing.JLabel();
        authorTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutTxtArea = new javax.swing.JTextArea();
        stockSpinner = new javax.swing.JSpinner();
        stockNotify = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuViewLog = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuBooks = new javax.swing.JMenu();
        menuLend = new javax.swing.JMenuItem();
        menuReturn = new javax.swing.JMenuItem();
        menuInsert = new javax.swing.JMenuItem();
        menuSearch = new javax.swing.JMenuItem();
        menuAuthors = new javax.swing.JMenu();
        menuAuthorInsert = new javax.swing.JMenuItem();
        menuViewAuthor = new javax.swing.JMenuItem();
        menuUsers = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        dialogAbout.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogAbout.setTitle("About this app");
        dialogAbout.setBackground(new java.awt.Color(156, 193, 194));
        dialogAbout.setResizable(false);
        dialogAbout.setSize(new java.awt.Dimension(439, 242));

        panelAbout.setBackground(new java.awt.Color(156, 193, 194));
        panelAbout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panelAbout.setPreferredSize(new java.awt.Dimension(427, 230));

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        labelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/external/images/libraryAbout.png"))); // NOI18N
        labelImage1.setToolTipText("Library logo");

        jScrollPane2.setHorizontalScrollBar(null);

        textAreaAbout.setEditable(false);
        textAreaAbout.setBackground(new java.awt.Color(156, 193, 194));
        textAreaAbout.setColumns(20);
        textAreaAbout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textAreaAbout.setForeground(new java.awt.Color(140, 112, 104));
        textAreaAbout.setRows(5);
        textAreaAbout.setText("Librarian App\n\nCreated by SoftGen Inc.\n\nversion: 1.41\nRelease date: 01/12/2024");
        textAreaAbout.setToolTipText("About this application");
        textAreaAbout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 210, 216), 3, true));
        textAreaAbout.setMargin(new java.awt.Insets(6, 6, 6, 6));
        textAreaAbout.setSelectedTextColor(new java.awt.Color(201, 210, 216));
        textAreaAbout.setSelectionColor(new java.awt.Color(140, 112, 104));
        jScrollPane2.setViewportView(textAreaAbout);

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(buttonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOK)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogAboutLayout = new javax.swing.GroupLayout(dialogAbout.getContentPane());
        dialogAbout.getContentPane().setLayout(dialogAboutLayout);
        dialogAboutLayout.setHorizontalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogAboutLayout.setVerticalGroup(
            dialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(titleTxt.getText());
        setResizable(false);
        setSize(new java.awt.Dimension(950, 750));

        jSplitPane.setBackground(new java.awt.Color(156, 193, 194));
        jSplitPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jSplitPane.setDividerLocation(315);
        jSplitPane.setDividerSize(8);
        jSplitPane.setToolTipText("");
        jSplitPane.setPreferredSize(new java.awt.Dimension(630, 470));
        labelbookID.setVisible(false);

        leftPane.setBackground(new java.awt.Color(156, 193, 194));
        leftPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        leftPane.setPreferredSize(new java.awt.Dimension(300, 230));

        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setText("jLabel1");

        javax.swing.GroupLayout leftPaneLayout = new javax.swing.GroupLayout(leftPane);
        leftPane.setLayout(leftPaneLayout);
        leftPaneLayout.setHorizontalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPaneLayout.setVerticalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPaneLayout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(labelImage)
                .addGap(357, 357, 357))
        );

        jSplitPane.setLeftComponent(leftPane);

        rightPane.setBackground(new java.awt.Color(156, 193, 194));
        rightPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        rightPane.setPreferredSize(new java.awt.Dimension(465, 350));

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(140, 112, 104));
        labelTitle.setText("Title");

        lendCatCombo.setBorder(null);
        lendCatCombo.setEnabled(false);

        titleTxt.setEditable(false);
        titleTxt.setBorder(null);
        titleTxt.setSelectionColor(new java.awt.Color(190, 132, 81));

        labelPubHouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPubHouse.setForeground(new java.awt.Color(140, 112, 104));
        labelPubHouse.setText("Publishing House");

        labelCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCategory.setForeground(new java.awt.Color(140, 112, 104));
        labelCategory.setText("Category");

        isbnTxt.setBorder(null);
        isbnTxt.setEnabled(false);
        isbnTxt.setSelectionColor(new java.awt.Color(190, 132, 81));

        pubHouseCombo.setBorder(null);
        pubHouseCombo.setEnabled(false);
        pubHouseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubHouseComboActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setVisible(false);
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Edit");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        pubDateTxt.setBorder(null);
        pubDateTxt.setEnabled(false);
        pubDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubDateTxtActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        labelPubDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPubDate.setForeground(new java.awt.Color(140, 112, 104));
        labelPubDate.setText("Publishing Date");

        labelLendCat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelLendCat.setForeground(new java.awt.Color(140, 112, 104));
        labelLendCat.setText("Lend Category");

        labelIsbn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelIsbn.setForeground(new java.awt.Color(140, 112, 104));
        labelIsbn.setText("ISBN");

        categoryCombo.setAutoscrolls(true);
        categoryCombo.setBorder(null);
        categoryCombo.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 112, 104));
        jLabel1.setText("Books available:");

        labelbookID.setEnabled(false);

        labelFullname.setText(User.getName() + " " + User.getSurname());
        labelFullname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFullname.setText(User.getName() + " " + User.getSurname());
        labelFullname.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        logOutBtn.setBackground(new java.awt.Color(156, 193, 194));
        logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setMnemonic('O');
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.setBorderPainted(false);
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.setDisplayedMnemonicIndex(4);
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });

        labelAuthor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelAuthor.setForeground(new java.awt.Color(140, 112, 104));
        labelAuthor.setText("Author(s)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 112, 104));
        jLabel2.setText("Abstract");

        aboutTxtArea.setColumns(20);
        aboutTxtArea.setLineWrap(true);
        aboutTxtArea.setRows(5);
        aboutTxtArea.setSelectionColor(new java.awt.Color(190, 132, 81));
        jScrollPane1.setViewportView(aboutTxtArea);

        stockSpinner.setEnabled(false);

        stockNotify.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stockNotify.setForeground(new java.awt.Color(193, 81, 135));

        javax.swing.GroupLayout rightPaneLayout = new javax.swing.GroupLayout(rightPane);
        rightPane.setLayout(rightPaneLayout);
        rightPaneLayout.setHorizontalGroup(
            rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPaneLayout.createSequentialGroup()
                        .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightPaneLayout.createSequentialGroup()
                                .addComponent(updateBtn)
                                .addGap(67, 67, 67)
                                .addComponent(cancelBtn))
                            .addGroup(rightPaneLayout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(labelbookID)))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPaneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rightPaneLayout.createSequentialGroup()
                                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelTitle)
                                    .addComponent(labelAuthor)
                                    .addComponent(jLabel2)
                                    .addComponent(labelCategory))
                                .addGap(73, 73, 73)
                                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pubDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pubHouseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lendCatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(authorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(rightPaneLayout.createSequentialGroup()
                                        .addComponent(stockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(stockNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(rightPaneLayout.createSequentialGroup()
                                .addComponent(labelFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logOutBtn)))
                        .addGap(72, 72, 72))))
            .addGroup(rightPaneLayout.createSequentialGroup()
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPaneLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backBtn))
                    .addGroup(rightPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLendCat)
                            .addComponent(labelPubHouse)
                            .addComponent(labelPubDate)
                            .addComponent(labelIsbn)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightPaneLayout.setVerticalGroup(
            rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelbookID)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthor))
                .addGap(18, 18, 18)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPubDate))
                .addGap(33, 33, 33)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPubHouse)
                    .addComponent(pubHouseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLendCat)
                    .addComponent(lendCatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIsbn)
                    .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockNotify))
                .addGap(51, 51, 51)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(cancelBtn)
                    .addComponent(updateBtn))
                .addGap(20, 20, 20))
        );

        jSplitPane.setRightComponent(rightPane);

        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuFile.setMnemonic('O');
        menuFile.setText("File");
        menuFile.setToolTipText("Actions about the Application");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuViewLog.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuViewLog.setMnemonic('g');
        menuViewLog.setText("View Log");
        menuViewLog.setToolTipText("Examine the application log");
        menuViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewLogActionPerformed(evt);
            }
        });
        menuFile.add(menuViewLog);

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuLogout.setText("Logout");
        menuLogout.setToolTipText("Exit safely from the application");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuFile.add(menuLogout);

        menuBar.add(menuFile);

        menuBooks.setMnemonic('S');
        menuBooks.setText("Books");
        menuBooks.setToolTipText("Actions about Books");
        menuBooks.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuBooksMenuSelected(evt);
            }
        });
        menuBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBooksMouseEntered(evt);
            }
        });
        menuBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBooksActionPerformed(evt);
            }
        });

        menuLend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuLend.setMnemonic('L');
        menuLend.setText("Lend a Book");
        menuLend.setToolTipText("Lend a book to a user");
        menuLend.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menuLendStateChanged(evt);
            }
        });
        menuLend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLendMouseEntered(evt);
            }
        });
        menuLend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLendActionPerformed(evt);
            }
        });
        menuBooks.add(menuLend);

        menuReturn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuReturn.setMnemonic('R');
        menuReturn.setText("Return Book");
        menuReturn.setToolTipText("Return a book to the Library");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        menuBooks.add(menuReturn);

        menuInsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuInsert.setMnemonic('I');
        menuInsert.setText("Register Book");
        menuInsert.setToolTipText("Register a new book to the Library");
        menuInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsertActionPerformed(evt);
            }
        });
        menuBooks.add(menuInsert);

        menuSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuSearch.setMnemonic('S');
        menuSearch.setText("Browse Books");
        menuSearch.setToolTipText("Find books based on title");
        menuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearchActionPerformed(evt);
            }
        });
        menuBooks.add(menuSearch);

        menuBar.add(menuBooks);

        menuAuthors.setText("Authors");
        menuAuthors.setToolTipText("Actions about Authors");

        menuAuthorInsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuAuthorInsert.setMnemonic('A');
        menuAuthorInsert.setText("Insert Author");
        menuAuthorInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAuthorInsertActionPerformed(evt);
            }
        });
        menuAuthors.add(menuAuthorInsert);

        menuViewAuthor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuViewAuthor.setMnemonic('V');
        menuViewAuthor.setText("View/Edit Author");
        menuViewAuthor.setToolTipText("View or Edit Authors");
        menuViewAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewAuthorActionPerformed(evt);
            }
        });
        menuAuthors.add(menuViewAuthor);

        menuBar.add(menuAuthors);

        menuUsers.setText("Users");
        menuUsers.setToolTipText("Actions about Users");
        menuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsersActionPerformed(evt);
            }
        });

        menuUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuUser.setMnemonic('U');
        menuUser.setText("Insert User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        menuUsers.add(menuUser);

        jMenuItem1.setText("View/Edit User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsers.add(jMenuItem1);

        menuBar.add(menuUsers);

        menuHelp.setText("Help");
        menuHelp.setToolTipText("Find help for issues");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setMnemonic('b');
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuHelp.add(jMenuItem4);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        enabledAll(false);
        cancelBtn.setVisible(false);
        updateBtn.setText("Edit");
        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
        stockNotify.setText("");
        fillInFormValues(Integer.parseInt(labelbookID.getText()));
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (updateBtn.getText().equalsIgnoreCase("Edit")) {
            updateBtn.setText("Update");
            enabledAll(true);
            cancelBtn.setVisible(true);
            updateBtn.setBackground(new java.awt.Color(193, 81, 135));
            backBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
        } else {
            if ((Integer) stockSpinner.getValue() < 1) {
            stockNotify.setText("Stock is expected to be greater than 1");
            stockSpinner.setFont(new java.awt.Font("Segoe UI", 1, 12));
            stockSpinner.setForeground(new java.awt.Color(255, 255, 255));
            stockSpinner.requestFocus();
            stockSpinner.setBackground(new java.awt.Color(193, 81, 135));
            return;
        } else {
            stockSpinner.setFont(new java.awt.Font("Segoe UI", 0, 12));
            stockSpinner.setForeground(new java.awt.Color(0, 0, 0));
            stockSpinner.setBackground(new java.awt.Color(255, 255, 255));
            stockNotify.setText("");
        }
            
            
            updateBtn.setText("Edit");
            enabledAll(false);
            cancelBtn.setVisible(true);
            updateBtn.setBackground(new java.awt.Color(255, 255, 255));
            boolean updated = false;
            int bookID = Integer.parseInt(labelbookID.getText());

            updated = BookHandler.updateBook(bookID, titleTxt.getText(), categoryCombo.getSelectedIndex() + 1,
                    pubDateTxt.getText(), pubHouseCombo.getSelectedIndex() + 1, lendCatCombo.getSelectedIndex() + 1,
                    isbnTxt.getText(), (Integer)stockSpinner.getValue());

            if (updated) {
                JOptionPane.showMessageDialog(null, "Book Updated successfully", "Book Update", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Error Updating Book!", "Book Update", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                fillInFormValues(bookID);
            }

        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        ViewBooks viewBooks = new ViewBooks();
        viewBooks.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void pubHouseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubHouseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pubHouseComboActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new java.awt.Color(201, 210, 216));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
    }//GEN-LAST:event_backBtnMouseExited

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        dialogAbout.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void menuViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewLogActionPerformed
        this.setVisible(false);
        ViewLog viewLog = new ViewLog();
        viewLog.setVisible(true);
    }//GEN-LAST:event_menuViewLogActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        try {
            LogHandler.insertActivityLog("User " + User.getUserid() + " "
                    + User.getName() + " " + User.getSurname() + " has logged off");
            User.clearValues();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        Initiator init = new Initiator();
        init.setVisible(true);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed

    }//GEN-LAST:event_menuFileActionPerformed

    private void menuLendStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menuLendStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLendStateChanged

    private void menuLendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLendMouseEntered

    }//GEN-LAST:event_menuLendMouseEntered

    private void menuLendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLendActionPerformed
        this.setVisible(false);
        LendBook lendBook = new LendBook();
        lendBook.setVisible(true);
    }//GEN-LAST:event_menuLendActionPerformed

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
        this.setVisible(false);
        ReturnBook returnBook = new ReturnBook();
        returnBook.setVisible(true);
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsertActionPerformed

    }//GEN-LAST:event_menuInsertActionPerformed

    private void menuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearchActionPerformed
        this.setVisible(false);
        ViewBooks viewBooks = new ViewBooks();
        viewBooks.setVisible(true);
    }//GEN-LAST:event_menuSearchActionPerformed

    private void menuBooksMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuBooksMenuSelected

    }//GEN-LAST:event_menuBooksMenuSelected

    private void menuBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBooksMouseEntered

    }//GEN-LAST:event_menuBooksMouseEntered

    private void menuBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBooksActionPerformed

    }//GEN-LAST:event_menuBooksActionPerformed

    private void menuAuthorInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAuthorInsertActionPerformed
        this.setVisible(false);
        InsertAuthor insAuth = new InsertAuthor();
        insAuth.setVisible(true);
    }//GEN-LAST:event_menuAuthorInsertActionPerformed

    private void menuViewAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewAuthorActionPerformed
        this.setVisible(false);
        ViewAuthors viewAuthors = new ViewAuthors();
        viewAuthors.setVisible(true);
    }//GEN-LAST:event_menuViewAuthorActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        this.setVisible(false);
        InsertUser insUser = new InsertUser();
        insUser.setVisible(true);
    }//GEN-LAST:event_menuUserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        ViewUsers viewUsers = new ViewUsers();
        viewUsers.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsersActionPerformed

    }//GEN-LAST:event_menuUsersActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dialogAbout.setLocationRelativeTo(this);
        dialogAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void pubDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pubDateTxtActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new java.awt.Color(193, 81, 135));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new java.awt.Color(156, 193, 194));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        cancelBtn.setBackground(new java.awt.Color(201, 210, 216));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12));
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        cancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
    }//GEN-LAST:event_cancelBtnMouseExited

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        if (updateBtn.getText().equalsIgnoreCase("Edit")) {
            updateBtn.setBackground(new java.awt.Color(201, 210, 216));
            updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12));
        }
        else if (updateBtn.getText().equalsIgnoreCase("Update")) {
            updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12));
            updateBtn.setForeground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        if (updateBtn.getText().equalsIgnoreCase("Edit")) {
            updateBtn.setBackground(new java.awt.Color(255, 255, 255));
            updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
        }
        else if (updateBtn.getText().equalsIgnoreCase("Update")) {
            updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
            updateBtn.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_updateBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBook().setVisible(true);
            }
        });
    }

    private void enabledAll(boolean visible) {
        cancelBtn.setVisible(visible);
        titleTxt.setEnabled(visible);
        categoryCombo.setEnabled(visible);
        pubDateTxt.setEnabled(visible);
        pubHouseCombo.setEnabled(visible);
        lendCatCombo.setEnabled(visible);
        isbnTxt.setEnabled(visible);
        stockSpinner.setEnabled(visible);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aboutTxtArea;
    private javax.swing.JLabel authorTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JDialog dialogAbout;
    private javax.swing.JTextField isbnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelFullname;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelImage1;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelLendCat;
    private javax.swing.JLabel labelPubDate;
    private javax.swing.JLabel labelPubHouse;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelbookID;
    private javax.swing.JPanel leftPane;
    private javax.swing.JComboBox<String> lendCatCombo;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JMenuItem menuAuthorInsert;
    private javax.swing.JMenu menuAuthors;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBooks;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuInsert;
    private javax.swing.JMenuItem menuLend;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JMenuItem menuSearch;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JMenu menuUsers;
    private javax.swing.JMenuItem menuViewAuthor;
    private javax.swing.JMenuItem menuViewLog;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JTextField pubDateTxt;
    private javax.swing.JComboBox<String> pubHouseCombo;
    private javax.swing.JPanel rightPane;
    private javax.swing.JLabel stockNotify;
    private javax.swing.JSpinner stockSpinner;
    private javax.swing.JTextArea textAreaAbout;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void fillInFormValues(int bookID) {
        rs = BookHandler.selectBooks(bookID);
        rsCat = BookHandler.selectBookCategories();
        rsPubHouses = PublHouseHandler.selectPublHouses();
        rsLendCat = LendHandler.selectLendCategories();

        try {
            rs.next();

            labelbookID.setText("" + rs.getInt(1));
            titleTxt.setText(rs.getString(2));
            while (rsCat.next()) {
                categoryCombo.addItem(rsCat.getString(2));
            }

            categoryCombo.setSelectedIndex(rs.getInt(3) - 1);
            pubDateTxt.setText(rs.getString(5));

            while (rsPubHouses.next()) {
                pubHouseCombo.addItem(rsPubHouses.getString(2));
            }
            pubHouseCombo.setSelectedIndex(rs.getInt(7) - 1);

            while (rsLendCat.next()) {
                lendCatCombo.addItem(rsLendCat.getString(2));
            }
            lendCatCombo.setSelectedIndex(rs.getInt(10) - 1);

            isbnTxt.setText(rs.getString(8));

            stockSpinner.setValue(Integer.parseInt(rs.getString(11)));
            //stockTxt.setText(rs.getString(11));
            authorTxt.setText(rs.getString(12));
            aboutTxtArea.setText(rs.getString(13));
        } catch (SQLException ex) {
            Logger.getLogger(ViewBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
