package librarian.gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import librarian.handlers.BookHandler;
import librarian.handlers.LendHandler;
import librarian.handlers.PublHouseHandler;
import librarian.handlers.UsersHandler;

/**
 *
 * @author Miltiadis Parcharidis 011873
 */
public class ViewBook extends javax.swing.JFrame {

    /**
     * Creates new form ViewBook
     */
    public ViewBook() {
        // do nothing
    }

    public ViewBook(int bookID) {
        initComponents();
        ResultSet rs = null;
        ResultSet rsCat = null;
        ResultSet rsPubHouses = null;
        ResultSet rsLendCat = null;

        rs = BookHandler.selectBooks(bookID);
        rsCat = BookHandler.selectBookCategories();
        rsPubHouses = PublHouseHandler.selectPublHouses();
        rsLendCat = LendHandler.selectLendCategories();

        try {
            rs.next();

            titleTxt.setText(rs.getString(2));
            while (rsCat.next()) {
                categoryCombo.addItem(rsCat.getString(2));
            }
            categoryCombo.setSelectedIndex(rs.getInt(3)-1);
            pubDateTxt.setText(rs.getString(5));

            while (rsPubHouses.next()) {
                pubHouseCombo.addItem(rsPubHouses.getString(2));
            }
            pubHouseCombo.setSelectedIndex(rs.getInt(7)-1);

            while (rsLendCat.next()) {
                lendCatCombo.addItem(rsLendCat.getString(2));
            }
            lendCatCombo.setSelectedIndex(rs.getInt(10)-1);

            isbnTxt.setText(rs.getString(8));
        } catch (SQLException ex) {
            Logger.getLogger(ViewBook.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        leftPane = new javax.swing.JPanel();
        rightPane = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        lendCatCombo = new javax.swing.JComboBox<>();
        titleTxt = new javax.swing.JTextField();
        labelPubHouse = new javax.swing.JLabel();
        labelCategory = new javax.swing.JLabel();
        isbnTxt = new javax.swing.JTextField();
        pubHouseCombo = new javax.swing.JComboBox<>();
        resetBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        pubDateTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        labelPubDate = new javax.swing.JLabel();
        labelLendCat = new javax.swing.JLabel();
        labelIsbn = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Book");
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        jSplitPane.setDividerLocation(200);
        jSplitPane.setDividerSize(8);
        jSplitPane.setToolTipText("");
        jSplitPane.setPreferredSize(new java.awt.Dimension(630, 470));

        leftPane.setPreferredSize(new java.awt.Dimension(300, 230));

        javax.swing.GroupLayout leftPaneLayout = new javax.swing.GroupLayout(leftPane);
        leftPane.setLayout(leftPaneLayout);
        leftPaneLayout.setHorizontalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        leftPaneLayout.setVerticalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(leftPane);

        rightPane.setPreferredSize(new java.awt.Dimension(300, 230));

        labelTitle.setText("Title");

        lendCatCombo.setBorder(null);
        lendCatCombo.setEnabled(false);

        titleTxt.setEditable(false);
        titleTxt.setBorder(null);

        labelPubHouse.setText("Publishing House");

        labelCategory.setText("Category");

        isbnTxt.setBorder(null);
        isbnTxt.setEnabled(false);

        pubHouseCombo.setEnabled(false);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        pubDateTxt.setBorder(null);
        pubDateTxt.setEnabled(false);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        labelPubDate.setText("Publishing Date");

        labelLendCat.setText("Lend Category");

        labelIsbn.setText("ISBN");

        categoryCombo.setAutoscrolls(true);
        categoryCombo.setBorder(null);
        categoryCombo.setEnabled(false);

        javax.swing.GroupLayout rightPaneLayout = new javax.swing.GroupLayout(rightPane);
        rightPane.setLayout(rightPaneLayout);
        rightPaneLayout.setHorizontalGroup(
            rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPaneLayout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(resetBtn)
                        .addGap(26, 26, 26)
                        .addComponent(updateBtn)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelPubHouse)
                                .addComponent(labelLendCat, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelPubDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(labelIsbn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(titleTxt)
                            .addComponent(categoryCombo, 0, 211, Short.MAX_VALUE)
                            .addComponent(pubDateTxt)
                            .addComponent(pubHouseCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lendCatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isbnTxt))
                        .addGap(16, 16, 16))))
        );
        rightPaneLayout.setVerticalGroup(
            rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPaneLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPaneLayout.createSequentialGroup()
                        .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pubDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pubHouseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lendCatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightPaneLayout.createSequentialGroup()
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPubDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPubHouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLendCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelIsbn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(rightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(updateBtn)
                    .addComponent(resetBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(rightPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed

    }//GEN-LAST:event_resetBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        /*     boolean updated = UsersHandler.updateUser(userID, isbnTxt.getText(), surnameTxt.getText(),
                pubHouseCombo.getSelectedIndex() + 1, mailTxt.getText(),
               lendCatCombo.getSelectedIndex(), pubDateTxt.getText());

        if (updated) {
            JOptionPane.showMessageDialog(null, "User Updated successfully", "Update User", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Error While Updating!", "Update User", JOptionPane.WARNING_MESSAGE);
            this.setVisible(false);
        }
        this.setVisible(false);
        ViewUsers viewUsers = new ViewUsers();
        viewUsers.setVisible(true);
         */
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        ViewBooks viewBooks = new ViewBooks();
        viewBooks.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JTextField isbnTxt;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelLendCat;
    private javax.swing.JLabel labelPubDate;
    private javax.swing.JLabel labelPubHouse;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel leftPane;
    private javax.swing.JComboBox<String> lendCatCombo;
    private javax.swing.JTextField pubDateTxt;
    private javax.swing.JComboBox<String> pubHouseCombo;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel rightPane;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
